### ISSUE TITLE
Renderer error

### ISSUE THREAD

**Issue by MaximSpirin** [VerizonAdPlatforms/OneMobileSDK-releases-android#2]
Hello,
we are getting the following error when playing aol playlists:

![exo_player_crash_codec](https://user-images.githubusercontent.com/730209/36092739-10d54e4a-0ff1-11e8-80a4-a2eef498c507.PNG)

Player enters into the crash loop and keeps throwing this error while switching between videos and then turns to RESTRICTED label on black background.

**Comment by AleksanderLevadniy** [comment]
Hi @MaximSpirin!

Most likely this issue is connected to some specific device. Stack trace shows error in codec. Could you kindly provide us with details such as: device vendor, os version on it,  sdk version.

**Comment by MaximSpirin** [comment]
Hello,
please look at the attached image:
![tab_e](https://user-images.githubusercontent.com/730209/36143024-8d0282dc-10b2-11e8-8e2f-4537650cc9e0.png)

**Comment by MaximSpirin** [comment]
Hello.
Could hardwareAccelerated=true tag improve this issue?

**Comment by AleksanderLevadniy** [comment]
Hi! Most likely this will not change anything. Do you have problem only with this device? Could you, kindly, try to run app in emulator?

**Comment by MaximSpirin** [comment]
Hello!
we are testing in on a couple new devices. The thing is that Tab E is our primary device that will be used massively so we would like to fix this problem asap.
Some additional info
every time this exception gets thrown the player itself calls ErrorListener.onError
It just happened with player when it was playing demo aol recycle ad which provoked an infinite ad loop - exo player throws an exception and cannot go to content. 
Please take a look at the attached screenshot. Is it audio or video codec that fails to work?

![image](https://user-images.githubusercontent.com/730209/36315031-52b54288-133f-11e8-93df-6e6c1740d58b.png)

**Comment by MarkGerl** [comment]
@AleksanderLevadniy do they need to catch this error, and handle it in a specific way?  Of course, the best solution is to have no error, or to code around the error.

**Comment by AndriiMoskvin** [comment]
The issue happens inside ExoPlayer - we should investigate why it happens on this particular device. Handling this error will not help in displaying video...

**Comment by AleksanderLevadniy** [comment]
@MaximSpirin Please, put full stacktrace. Could you also provide us with id of problematic video? How often does it happens? Could you try to reproduce this issue on emulator?

**Comment by AleksanderLevadniy** [comment]
This may be connected to content type, I think issue will go away when we will implement `mp4` extra field on MS

**Comment by perigelium** [comment]
This is full debug output for this error:

I/ACodec:  [] Now uninitialized
I/ACodec: [] onAllocateComponent
I/OMXClient: MuxOMX ctor
I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 4940859
I/ExtendedACodec: setupVideoDecoder()
I/ExtendedACodec: vpp-enable search is 0 and value is 0
E/ACodec:  configureCodec multi window instance fail  appPid : 4825
E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -5001
E/ACodec: signalError(omxError 0x80001001, internalError -5001)
E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
E/MediaCodec: configure failed with err 0xffffec77, resetting...
I/ACodec:  [OMX.qcom.video.decoder.avc] Now uninitialized
I/ACodec:  [] Now kWhatShutdownCompleted event : 8937
I/MediaCodec: Codec shutdown complete
I/ACodec:  [] Now uninitialized
I/ACodec: [] onAllocateComponent
I/OMXClient: MuxOMX ctor
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
E/ExoPlayerImplInternal: Renderer error.
                         com.google.android.exoplayer2.ExoPlaybackException
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:154)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                          Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1/27, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:154) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                          Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
                             at android.media.MediaCodec.native_configure(Native Method)
                             at android.media.MediaCodec.configure(MediaCodec.java:1884)
                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:405)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:154) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
I/ACodec:  [OMX.qcom.video.decoder.avc] Now kWhatShutdownCompleted event : 8937
I/MediaCodec: Codec shutdown complete
D/edison_inrideads: AolAdPlayerSingle - : useSDKforPlaylist: onPlayError - CONTENT_ERROR

**Comment by MaximSpirin** [comment]
@AleksanderLevadniy re:emulator - we have our own specifics: we dont distribute our app via google play and we use the same specific model of the tablet for mass roll-outs.
