### ISSUE TITLE
Could not allocate JNI Env

### ISSUE THREAD

**Issue by MaximSpirin** [VerizonAdPlatforms/OneMobileSDK-releases-android#4]
Hello.
We have just caught an error via Crashlytics:

Non-fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:731)
       at com.aol.mobile.sdk.x.a(Unknown Source)
       at com.aol.mobile.sdk.bo.a(Unknown Source)
       at com.aol.mobile.sdk.bq.a(Unknown Source)
       at com.aol.mobile.sdk.bf.onPlayerStateChanged(Unknown Source)
       at com.aol.mobile.sdk.player.Player.e(Unknown Source)
       at com.aol.mobile.sdk.e.a(Unknown Source)
       at com.aol.mobile.sdk.dc.onViewportResized(Unknown Source)
       at com.aol.mobile.sdk.renderer.a.a(Unknown Source)
       at com.aol.mobile.sdk.renderer.a.render(Unknown Source)
       at com.aol.mobile.sdk.renderer.ExoFlatRenderer.render(Unknown Source)
       at com.aol.mobile.sdk.f.onPlayerStateChanged(Unknown Source)
       at com.aol.mobile.sdk.player.Player.addPlayerStateObserver(Unknown Source)
       at com.aol.mobile.sdk.player.Binder.b(Unknown Source)
       at com.aol.mobile.sdk.player.Binder.setPlayer(Unknown Source)
       at com.edisoninteractive.inrideads.Presenters.AolAdPlayer$3.success(AolAdPlayer.java:254)
       at com.aol.mobile.sdk.player.VideoProvider$3.a(Unknown Source)
       at com.aol.mobile.sdk.player.VideoProvider$3.a(Unknown Source)
       at com.aol.mobile.sdk.x$7.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

Android version 7.1.1
SDK version 2.19
Device: Samsung Tab E

**Comment by AndriiMoskvin** [comment]
@OlegKozhemiakin @YaroslavKryvko Could you please take action here?
